### ISSUE TITLE
Two "ReferenceError: ... is not defined" issues

### ISSUE THREAD

**Issue by vfsfitvnm** [Kimbatt/js-Z#1]
Hi, I have encountered these issues:

1) Deobfuscation protection "skip" with zalgo (starting from zalgo level 33) leads to a `ReferenceError: ... is not defined` exception. The higher the zalgo level, the more this happens.

2) Deobfuscation protection "loop" leads to `ReferenceError: ... is not defined` exception, no matter what the charset is.

**Comment by Kimbatt** [comment]
Fixed!
The problem was with calculating which number variables were necessary. They were calculated based on the input text; we searched for the largest character code that appeared in the text, and generate variables up until that character (leaving out unnecessary number variables shortened the obfuscated code). But with the deobfuscation protection, we also used any characters that was present in the selected charset. So if the charset contained any characters which had character codes higher than the max char code in your input code, then the larger number variables were not defined. I fixed this by removing the part where we calculate largest char code; now we generate number variables until 32768. This makes the generated code a bit longer though. (Maybe the max charcode could be calculated based on the max char code in the selected charset, if deobfuscation protection is enabled)
